name: Setup
description: Setup node project

runs:
  using: 'composite'
  steps:
    - name: Configure node
      uses: actions/setup-node@v3

    - name: Install dependencies
      run: npm ci
      shell: bash
