name: Deploy App

on:
  pull_request:
    branches:
        - main
    
jobs:
  deploy:
    runs-on: windows-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: actions/setup-node@v3
        
      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build app
        run: npm run build

      - name: Install Vercel CLI
        if: ${{ inputs.deploy-vercel }}
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        if: ${{ inputs.deploy-vercel }}
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build for Vercel
        if: ${{ inputs.deploy-vercel }}
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        if: ${{ inputs.deploy-vercel }}
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}